_commit: 3.0.0
_src_path: https://github.com/flowtaleai/copier-python-uv
author_email: mtn@flowtale.ai
author_name: Flowtale
distribution_name: copier-python-uv
generate_docs: none
generate_example_code: false
git_hosting: gitlab
ide: vscode
license: MIT license
lint_dockerfile: false
max_line_length: 88
package_name: template
package_type: library
project_name: Copier Python UV
project_short_description: Opinionated copier template for python projects using uv
python_version: '3.12'
testing_framework: pytest
type_checker: none
use_jupyter_notebooks: false
use_lint_strict_rules: true
uv_version: 0.7.13
version: 3.0.0
